name: 'intermediate branch automations'
description: 'automate merge and pull request creation in intermediate branch'
author: 'Benedict Steven'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  SLACK_WEBHOOK_URL:
    description: 'Slack webhook'
    required: true
  SLACK_WEBHOOK_REVIEW_URL:
    description: 'slack webhook review url'
    required: true
  DESTINATION_BRANCH:
    description: 'destination branch'
    required: true
  TARGET_BRANCH:
    description: 'target branch'
    required: true
  TEAM_LEAD_ID:
    description: 'team lead id'
    required: false
  TECH_LEAD_ID:
    description: 'tech lead id'
    required: false
  REPO_OWNER:
    description: 'repository owner'
    required: true
  REPO_NAME:
    description: "repository name"
    required: true

runs:
  using: 'node16'
  main: 'action/index.js'

branding:
  icon: 'package'
  color: 'gray-dark'
