name: on pr to staging

on:
   schedule:
     - cron: '10-30 18 * * 0-6'

# on:
#    pull_request:
#      branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm install

      - name: Build
        run: npm run build

      - name: eod actions
        uses: ./
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_REVIEW_URL: ${{secrets.SLACK_WEBHOOK_REVIEW_URL}}
          TARGET_BRANCH: staging
          DESTINATION_BRANCH: master
          TEAM_LEAD_ID: ${{secrets.TEAM_LEAD_ID}}
          TECH_LEAD_ID: ${{secrets.TECH_LEAD_ID}}
