name: end of day

on:
   schedule:
    - cron: '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58 18,19,20,21,22,23,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,30 1,2,3,4,5,6,7,8,9,10,11,12 0-6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm install

      - name: Build
        run: npm run build

      - name: eod actions
        uses: ./
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_REVIEW_URL: ${{secrets.SLACK_WEBHOOK_REVIEW_URL}}
          TARGET_BRANCH: staging
          DESTINATION_BRANCH: master
          TEAM_LEAD_ID: ${{secrets.TEAM_LEAD_ID}}
          TECH_LEAD_ID: ${{secrets.TECH_LEAD_ID}}
          REPO_OWNER: bmsteven
          REPO_NAME: eod-actions
