name: on merging to develop

# on:
#    schedule:
#      - cron: '30 5 * * 1,3'
#      - cron: '30 5 * * 2,4'

on:
   pull_request:
     branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm install

      - name: Automatically create pr to staging
        uses: BaharaJr/merge-pr@0.0.1
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          # SLACK_WEBHOOK_REVIEW_URL: ${{secrets.SLACK_WEBHOOK_REVIEW_URL}}
          DESTINATION_BRANCH: staging

      # - name: install packages
      # - uses: ./
      #   with:
      #     GITHUB_TOKEN: ${{secrets.TOKEN}}
      #     SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
      #     # SLACK_WEBHOOK_REVIEW_URL: ${{secrets.SLACK_WEBHOOK_REVIEW_URL}}
      #     DESTINATION_BRANCH: staging