name: on merging to develop

on:
   schedule:
     - cron: '10 10 * * *'
    #  - cron: '10 10 * * 2,4'

# on:
#    push:
#      branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm install

      - name: Automatically create pr to staging
        uses: bmsteven/create_pr@1.0.5
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          # SLACK_WEBHOOK_REVIEW_URL: ${{secrets.SLACK_WEBHOOK_REVIEW_URL}}
          DESTINATION_BRANCH: staging