name: on pr to staging

# on:
#    schedule:
    #  - cron: '15 10 * * 0-6'
    #  - cron: '10 10 * * 2,4'

on:
   pull_request:
     branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm install

      - name: eod actions
        uses: ./
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_REVIEW_URL: ${{secrets.SLACK_WEBHOOK_REVIEW_URL}}
          TARGET_BRANCH: staging
          DESTINATION_BRANCH: master